import pandas as pd

'''
We will generate a series that contains boolean values which are generated by carrying out a certain logical operation
on a particular column of the dataframe
'''
world_df = pd.read_csv('E:/python/Data/parsed_country_data.csv')

'''
This returns a list which contains boolean values by carrying out the boolean operation on every element of the passed column
'''
rich_countries = world_df.GDP > 13205

'''
passing the aforementioned list as an argument to the data frame returns all the rows for which the boolean is .
The rows are returned as a DataFrame.
NOTE:
The index values of the rows are retained from the parent DataFrame. 
'''
print(type(world_df[rich_countries]))
rich_df = world_df[rich_countries]
print(rich_df['GDP'])


'''
Here is the shortcut of cutting down on all the above code:
'''
#rich_df = world_df[world_df.GDP > 13205]


